# Generated by Django 5.2.4 on 2025-07-24 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterUniqueTogether(
            name='phonetoken',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='phonetoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 24, 16, 46, 25, 239021, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='phonetoken',
            name='token',
            field=models.CharField(max_length=6),
        ),
    ]
