# Generated by Django 5.2.4 on 2025-07-24 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_alter_phonetoken_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonetoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 24, 16, 54, 24, 664417, tzinfo=datetime.timezone.utc)),
        ),
    ]
