# Generated by Django 5.2.4 on 2025-07-24 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_phonetoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonetoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 24, 17, 55, 45, 918870, tzinfo=datetime.timezone.utc)),
        ),
    ]
