# Generated by Django 5.2.4 on 2025-07-25 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_phonetoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonetoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 25, 10, 56, 3, 429104, tzinfo=datetime.timezone.utc)),
        ),
    ]
